Add trace to Redux Devtools Extension
fusionjs/fusion-plugin-react-redux pull request #200
Opened 2019-04-10 20:05 UTC by codalife

https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/Features/Trace.md

2019-04-10 20:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/fusionjs/fusion-plugin-react-redux?pullRequest=200) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/fusionjs/fusion-plugin-react-redux?pullRequest=200) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/fusionjs/fusion-plugin-react-redux?pullRequest=200) it.</sub>

2019-04-10 20:21 UTC, KevinGrandon requested changes
Thanks for the PR! Looks good to me, but we should remove the package-lock.json file since we use yarn for fusion development. Happy to send a contribution to your branch if helpful.

2019-04-10 21:03 UTC, codalife commented
> Thanks for the PR! Looks good to me, but we should remove the package-lock.json file since we use yarn for fusion development. Happy to send a contribution to your branch if helpful.

Removed lock. Rookie mistake

2019-04-10 23:11 UTC, chrisdothtml commented on package.json
> +  "version": "1.1.3",
You can also remove this change as we will bump the version through our release process

2019-04-12 16:21 UTC, mlmorg commented
We still want the `package.json`, you just don't need to bump the version since it will be handled by our release process.

2019-04-19 16:58 UTC, KevinGrandon submitted a review, later dismissed

2019-04-19 17:02 UTC, chrisdothtml approved these changes

2019-04-19 17:10 UTC, KevinGrandon commented
!merge

2019-04-19 17:10 UTC, merged